### ISSUE TITLE
Using LZO in `SquashFileSystemReader`

### ISSUE THREAD

**Issue by ww898** [LTRData/DiscUtils#19]
Hi @LTRData, this is the answer on your message https://github.com/DiscUtils/DiscUtils/issues/302#issuecomment-2410665848

I have just tried `LTRData.DiscUtils.SquashFs` v1.0.47 with `lzo.net` v0.0.6:
```
using var fsReader = new SquashFileSystemReader(fsStream, new SquashFileSystemReaderOptions
            {
                GetDecompressor = (kind, options) => kind switch
                {
                SquashFileSystemCompressionKind.Lzo => stream => new SeekableLzoStream(stream, CompressionMode.Decompress),
                _ => null
                }
            });
```
but unfortunately failed with exception:
```
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at DiscUtils.SquashFs.MetablockReader.Read(Span`1 buffer)
   at DiscUtils.SquashFs.Inode.Read(MetablockReader inodeReader)
   at DiscUtils.SquashFs.VfsSquashFileSystemReader..ctor(Stream stream, SquashFileSystemReaderOptions options)
   at DiscUtils.SquashFs.SquashFileSystemReader..ctor(Stream data, SquashFileSystemReaderOptions options)
```
Could you please help me?

**Comment by Olof-Lagerkvist** [comment]
I am not entire sure. But looking at the tests for this, it looks like it is supposed to be used in a slightly different way:
https://github.com/LTRData/DiscUtils/blob/27fc75729dd47925771ec25bc67407053d9f080e/Tests/LibraryTests/SquashFs/SquashFileSystemBuilderTest.cs#L200

**Comment by ww898** [comment]
Tried many different variants, but got the same exception. Could you please add test in your fork for LZO compression?

**Comment by Olof-Lagerkvist** [comment]
Yes sure, I'll take a look at it!

**Comment by Olof-Lagerkvist** [comment]
I just built an LZO compressed squashfs file system with one file and tried to decompress it using lzo.net in a similar way as you tested here. I also get some strange exception, but in my case somewhere within lzo.net library. I am not really familiar with that library, but I'll try to see if we somehow feed it with something that it does not expect. I have a bit limited time though, so it could take some time until I could look deeper into this.

**Comment by Olof-Lagerkvist** [comment]
There has unfortunately not been much work done about this for a long time. I suppose a long-term solution for supporting more compression formats with SquashFs would need integration with another third-party compression library that provides stream based compression in a way directly usable by this implementation.

I will close this as "not planned" for now and come back with a new discussion once there are new ideas about how to solve it.
